Editable kernel arguments
Vanilla-OS/ABRoot pull request #9
Opened 2023-01-02 18:06 UTC by matbme

While setting up Vanilla OS on my laptop, I found the need to add extra kernel parameters, but quickly realized that those parameters get replaced every time the root partition updates. This PR allows ABroot to read a string containing kernel parameters from `/etc/abroot/kargs` while updating the root partitions.

The only check I implemented so far is to make sure the string read from `kargs` doesn't end with a newline (which would break the config), but given the potential to make the system "unbootable", maybe it's a good idea to check the format as well. I think it's also a good idea to create a new file with the default parameters if it cannot be found, which would prevent the need for manual intervention if this gets merged. Please let me know your intentions so I can add this if you plan to merge this PR :)

2023-01-02 18:36 UTC, mirkobrombin commented
I had planned to work on this and had the same concept in mind. Thanks for the contribution!

I think we should consider not updating the kargs of the present partition as if the user makes errors, they will be reflected on both partitions, preventing the system from boot. My idea is to duplicate kargs on transaction start if it exists and use that only for the partition present.

Concerning the standard flags, we could define a kargs.default in /etc/abroot and install it together with ABRoot.

2023-01-02 18:39 UTC, matbme commented
> I think we should consider not updating the kargs of the present partition as if the user makes errors, they will be reflected on both partitions

Makes sense, I'll change that.

> we could define a kargs.default in /etc/abroot and install it together with ABRoot.

Do I do this by adding a new file to `./debian/abroot.install`?

2023-01-02 18:40 UTC, mirkobrombin commented
> Do I do this by adding a new file to ./debian/abroot.install?

adding it in /debian/etc/abroot/kargs.default should works

2023-01-02 21:38 UTC, matbme commented
ABroot now tries to read `/etc/abroot/kargs.default` if `/etc/abroot/kargs` can't be read.

2023-01-03 10:49 UTC, pietrodicaprio requested changes
See line comments

2023-01-03 10:49 UTC, pietrodicaprio commented on core/transaction.go
> +    kargsPath           = "/etc/abroot/kargs"
fix this indentation please

2023-01-03 10:49 UTC, pietrodicaprio commented on core/transaction.go
> +    kargs, err := GetKargs()
fix indentation please

2023-01-03 11:41 UTC, matbme commented
Classic tabs vs spaces problem 😅

2023-01-03 11:42 UTC, kbdharun commented
> Classic tabs vs spaces problem sweat_smile

Haha, Yeah

2023-01-03 11:50 UTC, pietrodicaprio commented
> Classic tabs vs spaces problem 😅

no problem, great job! 💯

2023-01-03 12:09 UTC, merged